--
-- PostgreSQL database dump
--

\restrict w0dsxFzCbhcCz3dX2YcOpq4snGpz1XF0hgdg4Kg4t7Sv75QK6akKyql0mBFx8cD

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admins (
    id integer NOT NULL,
    nom text NOT NULL,
    email text NOT NULL,
    mot_de_passe_hash text NOT NULL,
    role text DEFAULT 'technicien'::text NOT NULL,
    actif integer DEFAULT 1 NOT NULL,
    derniere_connexion timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: admins_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appareils; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.appareils (
    id integer NOT NULL,
    client_id integer,
    type text NOT NULL,
    marque text NOT NULL,
    modele text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT appareils_type_check CHECK ((type = ANY (ARRAY['telephone'::text, 'ordinateur'::text, 'tablette'::text, 'autre'::text])))
);


--
-- Name: appareils_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.appareils ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appareils_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.avis (
    id integer NOT NULL,
    nom text NOT NULL,
    note integer NOT NULL,
    commentaire text NOT NULL,
    statut text DEFAULT 'en_attente'::text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT avis_note_check CHECK (((note >= 1) AND (note <= 5))),
    CONSTRAINT avis_statut_check CHECK ((statut = ANY (ARRAY['en_attente'::text, 'valide'::text, 'refuse'::text])))
);


--
-- Name: avis_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.avis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories_appareils; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories_appareils (
    id integer NOT NULL,
    code text NOT NULL,
    titre text NOT NULL,
    description text NOT NULL,
    icone text,
    ordre integer DEFAULT 0 NOT NULL
);


--
-- Name: categories_appareils_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories_appareils ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_appareils_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clients (
    id integer NOT NULL,
    nom_complet text NOT NULL,
    telephone text NOT NULL,
    email text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contacts (
    id integer NOT NULL,
    nom text NOT NULL,
    email text,
    telephone text,
    sujet text,
    message text NOT NULL,
    traite integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: contacts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: demandes_reparation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.demandes_reparation (
    id integer NOT NULL,
    client_id integer NOT NULL,
    appareil_id integer NOT NULL,
    panne text NOT NULL,
    photo_path text,
    date_souhaitee text NOT NULL,
    heure_souhaitee text NOT NULL,
    confidentialite_acceptee integer DEFAULT 0 NOT NULL,
    statut_traitement text DEFAULT 'nouvelle'::text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: demandes_reparation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.demandes_reparation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.demandes_reparation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: faq; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.faq (
    id integer NOT NULL,
    question text NOT NULL,
    reponse text NOT NULL,
    ordre integer DEFAULT 0 NOT NULL
);


--
-- Name: faq_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.faq ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faq_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historique_reparation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historique_reparation (
    id integer NOT NULL,
    reparation_id integer NOT NULL,
    statut_id integer NOT NULL,
    commentaire text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: historique_reparation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.historique_reparation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historique_reparation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id integer NOT NULL,
    type text NOT NULL,
    destinataire text,
    contenu_resume text,
    statut text DEFAULT 'a_envoyer'::text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pieces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pieces (
    id integer NOT NULL,
    nom text NOT NULL,
    reference text
);


--
-- Name: pieces_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pieces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pieces_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: realisations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.realisations (
    id integer NOT NULL,
    titre text NOT NULL,
    type_appareil text NOT NULL,
    marque text,
    modele text,
    probleme text NOT NULL,
    intervention text NOT NULL,
    image_avant text,
    image_apres text,
    publie integer DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: realisations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.realisations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.realisations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rendez_vous; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rendez_vous (
    id integer NOT NULL,
    client_id integer NOT NULL,
    date_souhaitee text NOT NULL,
    heure_souhaitee text NOT NULL,
    motif text,
    statut text DEFAULT 'en_attente'::text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT rendez_vous_statut_check CHECK ((statut = ANY (ARRAY['en_attente'::text, 'confirme'::text, 'modifie'::text, 'refuse'::text])))
);


--
-- Name: rendez_vous_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rendez_vous ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rendez_vous_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reparation_pieces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reparation_pieces (
    id integer NOT NULL,
    reparation_id integer NOT NULL,
    piece_id integer NOT NULL,
    quantite integer DEFAULT 1 NOT NULL
);


--
-- Name: reparation_pieces_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reparation_pieces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reparation_pieces_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reparations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reparations (
    id integer NOT NULL,
    numero_fiche text NOT NULL,
    code_public text NOT NULL,
    client_id integer NOT NULL,
    appareil_id integer NOT NULL,
    demande_id integer,
    statut_id integer NOT NULL,
    description_statut text,
    diagnostic text,
    cout numeric,
    date_estimee_recuperation text,
    visible_publiquement integer DEFAULT 1 NOT NULL,
    devis_decision text DEFAULT 'en_attente'::text NOT NULL,
    devis_decision_date text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT reparations_devis_decision_check CHECK ((devis_decision = ANY (ARRAY['en_attente'::text, 'accepte'::text, 'refuse'::text])))
);


--
-- Name: reparations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reparations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reparations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.services (
    id integer NOT NULL,
    titre text NOT NULL,
    description text NOT NULL,
    icone text,
    ordre integer DEFAULT 0 NOT NULL
);


--
-- Name: services_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    cle text NOT NULL,
    valeur text
);


--
-- Name: statuts_reparation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.statuts_reparation (
    id integer NOT NULL,
    code text NOT NULL,
    libelle text NOT NULL,
    ordre integer NOT NULL
);


--
-- Name: statuts_reparation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.statuts_reparation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.statuts_reparation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admins admins_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_email_key UNIQUE (email);


--
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id);


--
-- Name: appareils appareils_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appareils
    ADD CONSTRAINT appareils_pkey PRIMARY KEY (id);


--
-- Name: avis avis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avis
    ADD CONSTRAINT avis_pkey PRIMARY KEY (id);


--
-- Name: categories_appareils categories_appareils_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories_appareils
    ADD CONSTRAINT categories_appareils_code_key UNIQUE (code);


--
-- Name: categories_appareils categories_appareils_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories_appareils
    ADD CONSTRAINT categories_appareils_pkey PRIMARY KEY (id);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: contacts contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_pkey PRIMARY KEY (id);


--
-- Name: demandes_reparation demandes_reparation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demandes_reparation
    ADD CONSTRAINT demandes_reparation_pkey PRIMARY KEY (id);


--
-- Name: faq faq_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faq
    ADD CONSTRAINT faq_pkey PRIMARY KEY (id);


--
-- Name: historique_reparation historique_reparation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historique_reparation
    ADD CONSTRAINT historique_reparation_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: pieces pieces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pieces
    ADD CONSTRAINT pieces_pkey PRIMARY KEY (id);


--
-- Name: realisations realisations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations
    ADD CONSTRAINT realisations_pkey PRIMARY KEY (id);


--
-- Name: rendez_vous rendez_vous_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rendez_vous
    ADD CONSTRAINT rendez_vous_pkey PRIMARY KEY (id);


--
-- Name: reparation_pieces reparation_pieces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reparation_pieces
    ADD CONSTRAINT reparation_pieces_pkey PRIMARY KEY (id);


--
-- Name: reparations reparations_code_public_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reparations
    ADD CONSTRAINT reparations_code_public_key UNIQUE (code_public);


--
-- Name: reparations reparations_numero_fiche_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reparations
    ADD CONSTRAINT reparations_numero_fiche_key UNIQUE (numero_fiche);


--
-- Name: reparations reparations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reparations
    ADD CONSTRAINT reparations_pkey PRIMARY KEY (id);


--
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (cle);


--
-- Name: statuts_reparation statuts_reparation_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.statuts_reparation
    ADD CONSTRAINT statuts_reparation_code_key UNIQUE (code);


--
-- Name: statuts_reparation statuts_reparation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.statuts_reparation
    ADD CONSTRAINT statuts_reparation_pkey PRIMARY KEY (id);


--
-- Name: appareils appareils_client_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appareils
    ADD CONSTRAINT appareils_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE;


--
-- Name: demandes_reparation demandes_reparation_appareil_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demandes_reparation
    ADD CONSTRAINT demandes_reparation_appareil_id_fkey FOREIGN KEY (appareil_id) REFERENCES public.appareils(id) ON DELETE CASCADE;


--
-- Name: demandes_reparation demandes_reparation_client_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demandes_reparation
    ADD CONSTRAINT demandes_reparation_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE;


--
-- Name: historique_reparation historique_reparation_reparation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historique_reparation
    ADD CONSTRAINT historique_reparation_reparation_id_fkey FOREIGN KEY (reparation_id) REFERENCES public.reparations(id) ON DELETE CASCADE;


--
-- Name: historique_reparation historique_reparation_statut_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historique_reparation
    ADD CONSTRAINT historique_reparation_statut_id_fkey FOREIGN KEY (statut_id) REFERENCES public.statuts_reparation(id);


--
-- Name: rendez_vous rendez_vous_client_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rendez_vous
    ADD CONSTRAINT rendez_vous_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE;


--
-- Name: reparation_pieces reparation_pieces_piece_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reparation_pieces
    ADD CONSTRAINT reparation_pieces_piece_id_fkey FOREIGN KEY (piece_id) REFERENCES public.pieces(id) ON DELETE CASCADE;


--
-- Name: reparation_pieces reparation_pieces_reparation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reparation_pieces
    ADD CONSTRAINT reparation_pieces_reparation_id_fkey FOREIGN KEY (reparation_id) REFERENCES public.reparations(id) ON DELETE CASCADE;


--
-- Name: reparations reparations_appareil_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reparations
    ADD CONSTRAINT reparations_appareil_id_fkey FOREIGN KEY (appareil_id) REFERENCES public.appareils(id) ON DELETE CASCADE;


--
-- Name: reparations reparations_client_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reparations
    ADD CONSTRAINT reparations_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE;


--
-- Name: reparations reparations_demande_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reparations
    ADD CONSTRAINT reparations_demande_id_fkey FOREIGN KEY (demande_id) REFERENCES public.demandes_reparation(id) ON DELETE SET NULL;


--
-- Name: reparations reparations_statut_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reparations
    ADD CONSTRAINT reparations_statut_id_fkey FOREIGN KEY (statut_id) REFERENCES public.statuts_reparation(id);


--
-- PostgreSQL database dump complete
--

\unrestrict w0dsxFzCbhcCz3dX2YcOpq4snGpz1XF0hgdg4Kg4t7Sv75QK6akKyql0mBFx8cD

